version: '2'
plugins:
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
