blank_issues_enabled: true
contact_links:
  - name: 问题提问 | Ask a question (GitHub Discussions)
    url: https://github.com/tryzealot/zealot/discussions
    about: 所有问题会放在 GitHub Discussions，GitHub issues 仅提供缺陷追踪和新特性相关，但我保留不回答的权利 | We use GitHub Discussions for questions, GitHub issues for tracking bug reports and feature requests
  - name: 电报技术讨论 | Chat on Telegram
    url: https://t.me/+csa3Y2KOx44wMGRl
    about: 开放技术沟通不意味着解答任何问题，发言前请带着脑子思考 | Open technical communication does not mean answering any questions, please think with your head before you speak
